# Generated by Django 5.2.7 on 2026-09-29 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('location', models.JSONField(default=dict)),
                ('work_mode', models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ON_SITE', 'On Site'), ('FLEXIBLE', 'Flexible')], max_length=20)),
                ('employment_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=20000)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openings', to='tenancy.businessunit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openings_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openings', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='HiringTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_team_assignments', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenantmembership')),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_team', to='recruiting.opening')),
            ],
        ),
        migrations.AddIndex(
            model_name='opening',
            index=models.Index(fields=['tenant', 'state', 'created_at'], name='recruiting__tenant__89e8d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='hiringteammember',
            constraint=models.UniqueConstraint(fields=('opening', 'membership'), name='uniq_opening_hiring_member'),
        ),
    ]
