# Generated by Django 5.2.17 on 2026-09-29 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0001_initial'),
        ('tenancy', '0005_emergencyaccessrequest_tenant_admin_notified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_profile_id', models.UUIDField()),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=20)),
                ('candidate_status', models.CharField(choices=[('APPLIED', 'Applied'), ('PROFILE_VIEWED', 'Profile Viewed'), ('SHORTLISTED', 'Shortlisted'), ('RECRUITER_INTERESTED', 'Recruiter Interested'), ('INTERVIEW_REQUESTED', 'Interview Requested'), ('OFFER_MADE', 'Offer Made'), ('NOT_SELECTED', 'Not Selected'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=40)),
                ('suggested_candidate_status', models.CharField(blank=True, choices=[('APPLIED', 'Applied'), ('PROFILE_VIEWED', 'Profile Viewed'), ('SHORTLISTED', 'Shortlisted'), ('RECRUITER_INTERESTED', 'Recruiter Interested'), ('INTERVIEW_REQUESTED', 'Interview Requested'), ('OFFER_MADE', 'Offer Made'), ('NOT_SELECTED', 'Not Selected'), ('WITHDRAWN', 'Withdrawn')], max_length=40, null=True)),
                ('answers', models.JSONField(default=dict)),
                ('consent_context_id', models.UUIDField(null=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('withdrawn_at', models.DateTimeField(null=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruiting.opening')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prior_state', models.CharField(blank=True, max_length=80)),
                ('new_state', models.CharField(max_length=80)),
                ('suggested_candidate_status', models.CharField(blank=True, choices=[('APPLIED', 'Applied'), ('PROFILE_VIEWED', 'Profile Viewed'), ('SHORTLISTED', 'Shortlisted'), ('RECRUITER_INTERESTED', 'Recruiter Interested'), ('INTERVIEW_REQUESTED', 'Interview Requested'), ('OFFER_MADE', 'Offer Made'), ('NOT_SELECTED', 'Not Selected'), ('WITHDRAWN', 'Withdrawn')], max_length=40, null=True)),
                ('published_candidate_status', models.CharField(blank=True, choices=[('APPLIED', 'Applied'), ('PROFILE_VIEWED', 'Profile Viewed'), ('SHORTLISTED', 'Shortlisted'), ('RECRUITER_INTERESTED', 'Recruiter Interested'), ('INTERVIEW_REQUESTED', 'Interview Requested'), ('OFFER_MADE', 'Offer Made'), ('NOT_SELECTED', 'Not Selected'), ('WITHDRAWN', 'Withdrawn')], max_length=40, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='recruiting.application')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterEnteredCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200)),
                ('location', models.JSONField(default=dict)),
                ('experience_years', models.DecimalField(decimal_places=2, max_digits=6)),
                ('skills', models.JSONField(default=list)),
                ('source_type', models.CharField(default='RECRUITER_ENTERED_SYNTHETIC', editable=False, max_length=40)),
                ('source_label', models.CharField(default='Recruiter-entered synthetic record', editable=False, max_length=80)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_entered_candidates', to='tenancy.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['tenant', 'state', 'updated_at'], name='recruiting__tenant__d7697b_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatusevent',
            index=models.Index(fields=['tenant', 'occurred_at'], name='recruiting__tenant__6abc97_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('opening', 'candidate_profile_id'), name='uniq_opening_candidate_application'),
        ),
        migrations.AddIndex(
            model_name='recruiterenteredcandidate',
            index=models.Index(fields=['tenant', 'created_at'], name='recruiting__tenant__bcba6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruiterenteredcandidate',
            constraint=models.CheckConstraint(condition=models.Q(('source_type', 'RECRUITER_ENTERED_SYNTHETIC')), name='recruiter_candidate_synthetic_source'),
        ),
        migrations.AddConstraint(
            model_name='recruiterenteredcandidate',
            constraint=models.CheckConstraint(condition=models.Q(('experience_years__gte', 0)), name='recruiter_candidate_nonnegative_experience'),
        ),
    ]
