# Generated by Django 5.2.17 on 2026-09-30 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_reconcile_finding_discovery_policy'),
        ('recruiting', '0003_foundation_rls'),
        ('tenancy', '0005_emergencyaccessrequest_tenant_admin_notified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='candidate_work_record_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='internal_status',
            field=models.CharField(blank=True, choices=[('SOURCED', 'Sourced'), ('SHORTLISTED', 'Shortlisted'), ('CONTACTED', 'Contacted'), ('SCREENING', 'Screening'), ('INTERVIEWING', 'Interviewing'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected'), ('NOT_RELEVANT', 'Not Relevant'), ('HIRED', 'Hired')], max_length=40),
        ),
        migrations.AddField(
            model_name='application',
            name='notify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='notify_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='candidate.resumeasset'),
        ),
        migrations.AddField(
            model_name='application',
            name='status_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status_published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_status_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ApplicationStatusPreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_status', models.CharField(choices=[('SOURCED', 'Sourced'), ('SHORTLISTED', 'Shortlisted'), ('CONTACTED', 'Contacted'), ('SCREENING', 'Screening'), ('INTERVIEWING', 'Interviewing'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected'), ('NOT_RELEVANT', 'Not Relevant'), ('HIRED', 'Hired')], max_length=40)),
                ('suggested_candidate_status', models.CharField(blank=True, choices=[('APPLIED', 'Applied'), ('PROFILE_VIEWED', 'Profile Viewed'), ('SHORTLISTED', 'Shortlisted'), ('RECRUITER_INTERESTED', 'Recruiter Interested'), ('INTERVIEW_REQUESTED', 'Interview Requested'), ('OFFER_MADE', 'Offer Made'), ('NOT_SELECTED', 'Not Selected'), ('WITHDRAWN', 'Withdrawn')], max_length=40, null=True)),
                ('application_version', models.PositiveBigIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='recruiting.application')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'application', 'expires_at'], name='recruiting__tenant__f687e0_idx')],
            },
        ),
    ]
