# Generated by Django 5.2.17 on 2026-09-30 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_reconcile_finding_discovery_policy'),
        ('recruiting', '0006_alter_application_closed_at_and_more'),
        ('tenancy', '0005_emergencyaccessrequest_tenant_admin_notified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('candidate_status__in', ['APPLIED', 'PROFILE_VIEWED', 'SHORTLISTED', 'RECRUITER_INTERESTED', 'INTERVIEW_REQUESTED', 'OFFER_MADE', 'NOT_SELECTED', 'WITHDRAWN'])), name='application_candidate_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('suggested_candidate_status__isnull', True), ('suggested_candidate_status__in', ['APPLIED', 'PROFILE_VIEWED', 'SHORTLISTED', 'RECRUITER_INTERESTED', 'INTERVIEW_REQUESTED', 'OFFER_MADE', 'NOT_SELECTED', 'WITHDRAWN']), _connector='OR'), name='application_suggested_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('internal_status', ''), ('internal_status__in', ['SOURCED', 'SHORTLISTED', 'CONTACTED', 'SCREENING', 'INTERVIEWING', 'OFFERED', 'REJECTED', 'NOT_RELEVANT', 'HIRED']), _connector='OR'), name='application_internal_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='applicationstatusevent',
            constraint=models.CheckConstraint(condition=models.Q(('suggested_candidate_status__isnull', True), ('suggested_candidate_status__in', ['APPLIED', 'PROFILE_VIEWED', 'SHORTLISTED', 'RECRUITER_INTERESTED', 'INTERVIEW_REQUESTED', 'OFFER_MADE', 'NOT_SELECTED', 'WITHDRAWN']), _connector='OR'), name='status_event_suggestion_valid'),
        ),
        migrations.AddConstraint(
            model_name='applicationstatusevent',
            constraint=models.CheckConstraint(condition=models.Q(('published_candidate_status__isnull', True), ('published_candidate_status__in', ['APPLIED', 'PROFILE_VIEWED', 'SHORTLISTED', 'RECRUITER_INTERESTED', 'INTERVIEW_REQUESTED', 'OFFER_MADE', 'NOT_SELECTED', 'WITHDRAWN']), _connector='OR'), name='status_event_publication_valid'),
        ),
        migrations.AddConstraint(
            model_name='applicationstatuspreview',
            constraint=models.CheckConstraint(condition=models.Q(('internal_status__in', ['SOURCED', 'SHORTLISTED', 'CONTACTED', 'SCREENING', 'INTERVIEWING', 'OFFERED', 'REJECTED', 'NOT_RELEVANT', 'HIRED'])), name='status_preview_internal_valid'),
        ),
        migrations.AddConstraint(
            model_name='applicationstatuspreview',
            constraint=models.CheckConstraint(condition=models.Q(('suggested_candidate_status__isnull', True), ('suggested_candidate_status__in', ['APPLIED', 'PROFILE_VIEWED', 'SHORTLISTED', 'RECRUITER_INTERESTED', 'INTERVIEW_REQUESTED', 'OFFER_MADE', 'NOT_SELECTED', 'WITHDRAWN']), _connector='OR'), name='status_preview_suggestion_valid'),
        ),
    ]
