# Generated by Django 5.2.17 on 2026-09-30 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0006_reconcile_finding_discovery_policy"),
        ("recruiting", "0007_application_application_candidate_status_valid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="consent_context_id",
            new_name="consent_context",
        ),
        migrations.AlterField(
            model_name="application",
            name="consent_context",
            field=models.ForeignKey(
                blank=True,
                db_column="consent_context_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="candidate.consentrecord",
            ),
        ),
    ]
