# Generated by Django 5.2.17 on 2026-09-30 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def clear_orphan_candidate_work_links(apps, schema_editor):
    application = apps.get_model("recruiting", "Application")
    candidate_work = apps.get_model("recruiting", "CandidateWorkRecord")
    valid_ids = candidate_work.objects.values_list("id", flat=True)
    application.objects.exclude(candidate_work_record__in=valid_ids).update(
        candidate_work_record=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_reconcile_finding_discovery_policy'),
        ('recruiting', '0010_application_candidate_disclosure_rls'),
        ('search', '0004_reconcile_phase4_schema'),
        ('tenancy', '0005_emergencyaccessrequest_tenant_admin_notified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateWorkRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_status', models.CharField(choices=[('SOURCED', 'Sourced'), ('SHORTLISTED', 'Shortlisted'), ('CONTACTED', 'Contacted'), ('SCREENING', 'Screening'), ('INTERVIEWING', 'Interviewing'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected'), ('NOT_RELEVANT', 'Not Relevant'), ('HIRED', 'Hired')], default='SOURCED', max_length=40)),
                ('shortlisted', models.BooleanField(default=False)),
                ('shortlist_order', models.PositiveIntegerField(blank=True, null=True)),
                ('structured_reasons', models.JSONField(blank=True, default=list)),
                ('explanatory_note_ciphertext', models.BinaryField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_work', to='candidate.candidateprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_work_created', to=settings.AUTH_USER_MODEL)),
                ('opening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_work_records', to='recruiting.opening')),
                ('originating_search', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_work_records', to='search.searchdefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_work_records', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_work_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='application',
            old_name='candidate_work_record_id',
            new_name='candidate_work_record',
        ),
        migrations.RunPython(clear_orphan_candidate_work_links, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='application',
            name='candidate_work_record',
            field=models.ForeignKey(blank=True, db_column='candidate_work_record_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_applications', to='recruiting.candidateworkrecord'),
        ),
        migrations.CreateModel(
            name='DisclosureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=200)),
                ('destination_type', models.CharField(max_length=40)),
                ('destination_identifier_ciphertext', models.BinaryField()),
                ('destination_preview', models.CharField(max_length=200)),
                ('requested_fields', models.JSONField(blank=True, default=list)),
                ('permitted_fields', models.JSONField(blank=True, default=list)),
                ('excluded_fields', models.JSONField(blank=True, default=list)),
                ('preview_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('PREVIEWED', 'Previewed'), ('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PREVIEWED', max_length=20)),
                ('result_category', models.CharField(blank=True, max_length=80)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disclosures', to='recruiting.application')),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='candidate.candidateprofile')),
                ('candidate_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disclosures', to='recruiting.candidateworkrecord')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_disclosures', to=settings.AUTH_USER_MODEL)),
                ('consent_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidate.consentrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body_ciphertext', models.BinaryField()),
                ('hiring_team_visible', models.BooleanField(default=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_notes', to='recruiting.application')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('candidate_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='recruiting.candidateworkrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitingStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prior_status', models.CharField(blank=True, max_length=40)),
                ('new_status', models.CharField(choices=[('SOURCED', 'Sourced'), ('SHORTLISTED', 'Shortlisted'), ('CONTACTED', 'Contacted'), ('SCREENING', 'Screening'), ('INTERVIEWING', 'Interviewing'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected'), ('NOT_RELEVANT', 'Not Relevant'), ('HIRED', 'Hired')], max_length=40)),
                ('structured_reasons', models.JSONField(blank=True, default=list)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_status_history', to='recruiting.application')),
                ('candidate_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='recruiting.candidateworkrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ShortlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_entry', to='recruiting.application')),
                ('candidate_work', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_entry', to='recruiting.candidateworkrecord')),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='candidateworkrecord',
            index=models.Index(fields=['tenant', 'opening', 'internal_status'], name='recruiting__tenant__8b6a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateworkrecord',
            index=models.Index(fields=['tenant', 'candidate_profile', 'updated_at'], name='recruiting__tenant__3eb2cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidateworkrecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'candidate_profile', 'originating_search'), name='uniq_candidate_work_context'),
        ),
        migrations.AddConstraint(
            model_name='candidateworkrecord',
            constraint=models.CheckConstraint(condition=models.Q(('internal_status__in', ['SOURCED', 'SHORTLISTED', 'CONTACTED', 'SCREENING', 'INTERVIEWING', 'OFFERED', 'REJECTED', 'NOT_RELEVANT', 'HIRED'])), name='candidate_work_internal_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='candidateworkrecord',
            constraint=models.CheckConstraint(condition=models.Q(('shortlisted', True), ('shortlist_order__isnull', True), _connector='OR'), name='candidate_work_order_requires_shortlist'),
        ),
        migrations.AddIndex(
            model_name='disclosurerequest',
            index=models.Index(fields=['tenant', 'candidate_profile', 'created_at'], name='recruiting__tenant__80e8c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='disclosurerequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application__isnull', True), ('candidate_work__isnull', False)), models.Q(('application__isnull', False), ('candidate_work__isnull', True)), _connector='OR'), name='disclosure_exactly_one_context'),
        ),
        migrations.AddIndex(
            model_name='recruiternote',
            index=models.Index(fields=['tenant', 'created_at'], name='recruiting__tenant__42bc4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruiternote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application__isnull', True), ('candidate_work__isnull', False)), models.Q(('application__isnull', False), ('candidate_work__isnull', True)), _connector='OR'), name='recruiter_note_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='recruitingstatusevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application__isnull', True), ('candidate_work__isnull', False)), models.Q(('application__isnull', False), ('candidate_work__isnull', True)), _connector='OR'), name='status_event_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='shortlistentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application__isnull', True), ('candidate_work__isnull', False)), models.Q(('application__isnull', False), ('candidate_work__isnull', True)), _connector='OR'), name='shortlist_entry_exactly_one_owner'),
        ),
    ]
