# Generated by Django 5.2.17 on 2026-09-29 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('recruiting', '0003_foundation_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_token', models.BinaryField(unique=True)),
                ('deletion_scope', models.JSONField(default=list)),
                ('source_completion', models.JSONField(default=dict)),
                ('backup_cutoff', models.DateTimeField()),
                ('replay_status', models.CharField(default='PENDING', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_hash', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DataRightsRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('ACCESS', 'Access'), ('CORRECTION', 'Correction'), ('WITHDRAW_CONSENT', 'Withdraw Consent'), ('HIDE_PROFILE', 'Hide Profile'), ('EXPORT', 'Export'), ('DELETE', 'Delete')], max_length=30)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('HELD', 'Held'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('scope', models.JSONField(default=dict)),
                ('correction', models.JSONField(default=dict)),
                ('step_up_evidence_id', models.UUIDField(blank=True, null=True)),
                ('consequence_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('expected_completion_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('safe_detail', models.CharField(blank=True, max_length=500)),
                ('support_escalated_at', models.DateTimeField(blank=True, null=True)),
                ('failure_category', models.CharField(blank=True, max_length=100)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rights_requests', to='candidate.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.JSONField(default=list)),
                ('authority_reference', models.CharField(max_length=200)),
                ('encrypted_rationale', models.BinaryField()),
                ('starts_at', models.DateTimeField()),
                ('review_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_holds', to='candidate.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RightsEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_ciphertext', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='privacy.datarightsrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RightsExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('object_key', models.CharField(blank=True, max_length=500)),
                ('payload_ciphertext', models.BinaryField(blank=True, null=True)),
                ('content_manifest', models.JSONField(default=dict)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('failure_category', models.CharField(blank=True, max_length=100)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='export', to='privacy.datarightsrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveProcessRetentionException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('policy_version', models.CharField(max_length=50)),
                ('legal_basis', models.CharField(max_length=200)),
                ('retained_data_scope', models.JSONField(default=list)),
                ('lifecycle_state', models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('review_date', models.DateTimeField()),
                ('terminating_event', models.CharField(max_length=200)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('audit_references', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retention_exceptions', to='recruiting.application')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retention_exceptions', to='candidate.candidateprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'lifecycle_state', 'review_date'], name='privacy_act_profile_e7199c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='datarightsrequest',
            index=models.Index(fields=['profile', 'state', 'submitted_at'], name='privacy_dat_profile_ab76ca_idx'),
        ),
    ]
