# Generated by Django 5.2.7 on 2026-09-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='actor_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='correlation_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='tenant_id',
            field=models.UUIDField(null=True),
        ),
    ]
