# Generated by Django 5.2.17 on 2026-09-30

import django.db.models.deletion
import modules.operations.models
import uuid
from django.conf import settings
from django.db import migrations, models


RLS_SQL = r"""
ALTER TABLE operations_workflowrun ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations_workflowrun FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON operations_workflowrun
USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
"""

RLS_REVERSE = r"""
DROP POLICY IF EXISTS tenant_isolation ON operations_workflowrun;
ALTER TABLE operations_workflowrun DISABLE ROW LEVEL SECURITY;
"""


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(RLS_SQL)


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(RLS_REVERSE)


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_outboxevent_actor_id_outboxevent_correlation_id_and_more"),
        (
            "tenancy",
            "0005_emergencyaccessrequest_tenant_admin_notified_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("workflow_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AWAITING_REVIEW", "Awaiting Review"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_step", models.CharField(max_length=100)),
                ("input_hash", models.CharField(max_length=64)),
                ("model_version", models.CharField(blank=True, max_length=200)),
                ("prompt_version", models.CharField(max_length=100)),
                ("checkpoint_ciphertext", models.BinaryField()),
                (
                    "expires_at",
                    models.DateTimeField(default=modules.operations.models.workflow_review_expiry),
                ),
                ("last_error_category", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenancy.tenant"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "actor", "status", "expires_at"],
                        name="operations__tenant__ea8233_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("created_at"))),
                        name="workflow_expiry_after_creation",
                    )
                ],
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
