# Generated by Django 5.2.17 on 2026-09-29 12:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name_ciphertext', models.BinaryField(default=bytes)),
                ('location', models.JSONField(default=dict)),
                ('headline', models.CharField(blank=True, max_length=300)),
                ('current_role', models.CharField(blank=True, max_length=200)),
                ('current_company', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('role_categories', models.JSONField(default=list)),
                ('preferred_locations', models.JSONField(default=list)),
                ('work_arrangements', models.JSONField(default=list)),
                ('meaningful_work', models.CharField(blank=True, max_length=300)),
                ('notice_period', models.CharField(blank=True, max_length=100)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('compensation_ciphertext', models.BinaryField(blank=True, null=True)),
                ('contact_preferences', models.JSONField(default=dict)),
                ('profile_state', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW_REQUIRED', 'Review Required'), ('PUBLISHED', 'Published'), ('HIDDEN', 'Hidden'), ('DELETION_PENDING', 'Deletion Pending'), ('DELETED', 'Deleted')], default='DRAFT', max_length=30)),
                ('last_candidate_activity_at', models.DateTimeField(auto_now_add=True)),
                ('consent_expires_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=30)),
                ('value_ciphertext', models.BinaryField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('purpose_scope', models.JSONField(default=list)),
                ('field_visibility', models.JSONField(default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='candidate.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('provenance', models.CharField(default='CANDIDATE_REPORTED', max_length=30)),
                ('review_state', models.CharField(default='ACCEPTED', max_length=20)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='candidate.candidateprofile')),
            ],
            options={
                'ordering': ('ordering', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=100)),
                ('field_scope', models.JSONField(default=list)),
                ('audience_scope', models.JSONField(default=dict)),
                ('notice_version', models.CharField(max_length=50)),
                ('affirmative_action', models.CharField(max_length=100)),
                ('locale', models.CharField(default='en-IN', max_length=20)),
                ('source_request_id', models.CharField(max_length=100)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='candidate.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=300)),
                ('role_title', models.CharField(blank=True, max_length=300)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_date_state', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('SUGGESTED', 'Suggested'), ('AMBIGUOUS', 'Ambiguous'), ('MISSING', 'Missing')], max_length=20)),
                ('end_date_state', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('SUGGESTED', 'Suggested'), ('AMBIGUOUS', 'Ambiguous'), ('MISSING', 'Missing')], max_length=20)),
                ('start_date_precision', models.CharField(choices=[('DAY', 'Day'), ('MONTH', 'Month'), ('YEAR', 'Year'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('end_date_precision', models.CharField(choices=[('DAY', 'Day'), ('MONTH', 'Month'), ('YEAR', 'Year'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('is_current', models.BooleanField(default=False)),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('INTERNSHIP', 'Internship'), ('APPRENTICESHIP', 'Apprenticeship'), ('FIXED_TERM_CONTRACT', 'Fixed Term Contract'), ('CONSULTING', 'Consulting'), ('SEASONAL', 'Seasonal'), ('OTHER_TEMPORARY', 'Other Temporary'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], max_length=30)),
                ('employment_type_state', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('SUGGESTED', 'Suggested'), ('AMBIGUOUS', 'Ambiguous'), ('MISSING', 'Missing')], max_length=20)),
                ('provenance', models.CharField(choices=[('CANDIDATE_REPORTED', 'Candidate Reported'), ('RESUME_EXTRACTED', 'Resume Extracted')], max_length=30)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('source_spans', models.JSONField(default=list)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='candidate.candidateprofile')),
            ],
            options={
                'ordering': ('ordering', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProfileEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fact_type', models.CharField(max_length=100)),
                ('normalized_value', models.JSONField()),
                ('provenance', models.CharField(max_length=40)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('visibility_scope', models.JSONField(default=dict)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='candidate.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_url', models.URLField(max_length=500)),
                ('display_label', models.CharField(blank=True, max_length=100)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='candidate.candidateprofile')),
            ],
            options={
                'ordering': ('ordering', 'normalized_url'),
            },
        ),
        migrations.CreateModel(
            name='ResumeAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quarantine_key', models.CharField(max_length=500, unique=True)),
                ('clean_key', models.CharField(blank=True, max_length=500)),
                ('original_filename_ciphertext', models.BinaryField()),
                ('declared_mime', models.CharField(max_length=150)),
                ('detected_mime', models.CharField(blank=True, max_length=150)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('scan_status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('SCANNING', 'Scanning'), ('CLEAN', 'Clean'), ('SCAN_FAILED', 'Scan Failed'), ('REJECTED', 'Rejected')], default='UPLOADING', max_length=20)),
                ('parse_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PARSING', 'Parsing'), ('REVIEW_REQUIRED', 'Review Required'), ('READY', 'Ready'), ('PARSE_FAILED', 'Parse Failed')], default='NOT_STARTED', max_length=30)),
                ('scan_provider_ref', models.CharField(blank=True, max_length=200)),
                ('is_current', models.BooleanField(default=True)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='candidate.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fact_type', models.CharField(max_length=100)),
                ('normalized_value', models.JSONField(blank=True, null=True)),
                ('source_excerpt_ciphertext', models.BinaryField(blank=True, null=True)),
                ('source_spans', models.JSONField(default=list)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('extraction_method', models.CharField(max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('ACCEPTED', 'Accepted'), ('CORRECTED', 'Corrected'), ('REJECTED', 'Rejected')], default='SUGGESTED', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='candidate.resumeasset')),
            ],
        ),
        migrations.CreateModel(
            name='VisibilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('APPROVED_RECRUITERS', 'Approved Recruiters'), ('MATCHING_ROLES', 'Matching Roles'), ('APPLIED_ROLES_ONLY', 'Applied Roles Only'), ('NOT_LOOKING', 'Not Looking')], max_length=30)),
                ('approved_tenant_ids', models.JSONField(default=list)),
                ('matching_preferences', models.JSONField(default=dict)),
                ('effective_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('policy_version', models.CharField(default='visibility-v1', max_length=50)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('consent_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidate.consentrecord')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility_rules', to='candidate.candidateprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['profile_state', 'updated_at'], name='candidate_c_profile_58a88c_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidateprofile',
            constraint=models.CheckConstraint(condition=models.Q(('experience_years__gte', 0)), name='candidate_nonnegative_experience'),
        ),
        migrations.AddConstraint(
            model_name='candidatecontact',
            constraint=models.UniqueConstraint(fields=('profile', 'channel'), name='uniq_candidate_contact'),
        ),
        migrations.AddConstraint(
            model_name='candidateskill',
            constraint=models.UniqueConstraint(fields=('profile', 'normalized_name'), name='uniq_candidate_normalized_skill'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['profile', 'purpose', 'withdrawn_at'], name='candidate_c_profile_a5c12e_idx'),
        ),
        migrations.AddConstraint(
            model_name='employmentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='employment_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='employmentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), ('end_date__isnull', True), _connector='OR'), name='current_employment_has_no_end_date'),
        ),
        migrations.AddConstraint(
            model_name='employmentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('start_date_state__in', ['AMBIGUOUS', 'MISSING']), ('start_date__isnull', False), _connector='OR'), name='known_employment_start_has_value'),
        ),
        migrations.AddConstraint(
            model_name='employmentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('end_date_state__in', ['AMBIGUOUS', 'MISSING']), ('end_date__isnull', False), _connector='OR'), name='known_employment_end_has_value'),
        ),
        migrations.AddConstraint(
            model_name='profilelink',
            constraint=models.UniqueConstraint(fields=('profile', 'normalized_url'), name='uniq_profile_link'),
        ),
        migrations.AddConstraint(
            model_name='resumeasset',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_current', True)), fields=('profile',), name='uniq_current_candidate_resume'),
        ),
        migrations.AddConstraint(
            model_name='visibilityrule',
            constraint=models.UniqueConstraint(condition=models.Q(('superseded_at__isnull', True)), fields=('profile',), name='uniq_current_visibility_rule'),
        ),
    ]
