# Generated by Django 5.2.17 on 2026-09-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidate_owner_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecontact',
            name='field_visibility',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='candidatecontact',
            name='purpose_scope',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='contact_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='location',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='preferred_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='role_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='work_arrangements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='employmentrecord',
            name='source_spans',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='extractedfact',
            name='source_spans',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profileevidence',
            name='visibility_scope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='visibilityrule',
            name='approved_tenant_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='visibilityrule',
            name='matching_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
