# Generated by Django 5.2.17 on 2026-09-30 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidatecontact_field_visibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('severity', models.CharField(default='INFORMATIONAL', max_length=30)),
                ('result', models.CharField(choices=[('FOUND', 'Found'), ('NOT_FOUND', 'Not Found'), ('INSUFFICIENT_DATA', 'Insufficient Data'), ('EXCLUDED', 'Excluded')], max_length=30)),
                ('source_record_type', models.CharField(max_length=80)),
                ('source_record_id', models.UUIDField()),
                ('source_record_version', models.PositiveBigIntegerField()),
                ('evidence', models.JSONField(default=dict)),
                ('message_key', models.CharField(max_length=120)),
                ('calculation_version', models.CharField(max_length=100)),
                ('evaluated_at', models.DateTimeField()),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('audit_references', models.JSONField(blank=True, default=list)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='candidate.candidateprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'code', 'result', 'superseded_at'], name='candidate_c_profile_c77146_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('superseded_at__isnull', True)), fields=('profile', 'code', 'source_record_type', 'source_record_id', 'calculation_version'), name='uniq_active_candidate_finding_evaluation'), models.CheckConstraint(condition=models.Q(('severity', 'INFORMATIONAL')), name='candidate_finding_informational_only')],
            },
        ),
    ]
