# Generated by Django 5.2.7 on 2026-09-29 06:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkpoint_date', models.DateField(unique=True)),
                ('terminal_hash', models.CharField(max_length=64)),
                ('signature', models.BinaryField()),
                ('object_key', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_id', models.UUIDField(editable=False, null=True)),
                ('action', models.CharField(editable=False, max_length=160)),
                ('target_type', models.CharField(editable=False, max_length=100)),
                ('target_id', models.CharField(blank=True, editable=False, max_length=100)),
                ('purpose_code', models.CharField(blank=True, editable=False, max_length=100)),
                ('outcome', models.CharField(editable=False, max_length=20)),
                ('metadata', models.JSONField(default=dict, editable=False)),
                ('previous_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('event_hash', models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
            },
        ),
    ]
