# Generated by Django 5.2.7 on 2026-09-29 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=160)),
                ('legal_boundary_reference', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='PROVISIONING', max_length=20)),
                ('default_timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('retention_policy_version', models.CharField(default='launch-v1', max_length=80)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'CLOSED'), _negated=True), fields=('slug',), name='uniq_active_tenant_slug')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(max_length=100)),
                ('reason', models.TextField(max_length=2000)),
                ('incident_reference', models.CharField(max_length=200)),
                ('object_scope', models.JSONField(default=dict)),
                ('field_scope', models.JSONField(default=list)),
                ('operation_scope', models.JSONField(default=list)),
                ('requested_minutes', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='REQUESTED', max_length=20)),
                ('approved_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emergency_approvals', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_requests', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emergency_revocations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose_code', models.CharField(max_length=100)),
                ('field_scope', models.JSONField(default=list)),
                ('object_scope', models.JSONField(default=dict)),
                ('valid_from', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_units', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('tenant', 'name'), name='uniq_active_business_unit_name')],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('RECRUITER', 'Recruiter'), ('HIRING_MANAGER', 'Hiring Manager'), ('TENANT_ADMIN', 'Tenant Admin')], max_length=30)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='INVITED', max_length=20)),
                ('scope', models.JSONField(default=dict)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'identity'), name='uniq_tenant_identity_membership')],
            },
        ),
    ]
