# Generated by Django 5.2.17 on 2026-09-29 07:23

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='businessunit',
            name='uniq_active_business_unit_name',
        ),
        migrations.RemoveConstraint(
            model_name='tenant',
            name='uniq_active_tenant_slug',
        ),
        migrations.AddConstraint(
            model_name='businessunit',
            constraint=models.UniqueConstraint(models.F('tenant'), django.db.models.functions.text.Lower('name'), condition=models.Q(('status', 'ACTIVE')), name='uniq_active_business_unit_name'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), condition=models.Q(('status', 'CLOSED'), _negated=True), name='uniq_active_tenant_slug'),
        ),
    ]
