# Generated by Django 5.2.17 on 2026-09-29 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_alter_emergencyaccessrequest_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyaccessrequest',
            name='tenant_admin_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['tenant', 'grantee', 'status', 'expires_at'], name='tenancy_acc_tenant__1418f7_idx'),
        ),
    ]
