# Generated by Django 5.2.17 on 2026-10-01 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_emergencyaccessrequest_tenant_admin_notified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('MEMBERSHIP', 'Membership'), ('PRIVILEGED_ROLE', 'Privileged Role'), ('PURPOSE_GRANT', 'Purpose Grant'), ('EMERGENCY_GRANT', 'Emergency Grant'), ('AUDIT_ACCESS', 'Audit Access')], max_length=30)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('population_snapshot', models.JSONField(default=list)),
                ('population_hash', models.CharField(max_length=64)),
                ('due_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_counts', models.JSONField(default=dict)),
                ('findings', models.JSONField(default=list)),
                ('revocations', models.JSONField(default=list)),
                ('remediation_state', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='NOT_REQUIRED', max_length=20)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_access_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_access_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_reviews', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AccessReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('MEMBERSHIP', 'Membership'), ('PRIVILEGED_ROLE', 'Privileged Role'), ('PURPOSE_GRANT', 'Purpose Grant'), ('EMERGENCY_GRANT', 'Emergency Grant'), ('AUDIT_ACCESS', 'Audit Access')], max_length=30)),
                ('source_object_id', models.CharField(max_length=100)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('evidence', models.JSONField(default=dict)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('RETAIN', 'Retain'), ('REVOKE', 'Revoke'), ('EXCEPTION', 'Exception')], default='PENDING', max_length=20)),
                ('finding', models.CharField(blank=True, max_length=500)),
                ('exception_expires_at', models.DateTimeField(blank=True, null=True)),
                ('remediation_state', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='NOT_REQUIRED', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exception_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_access_review_exceptions', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenancy.accessreview')),
            ],
        ),
        migrations.AddIndex(
            model_name='accessreview',
            index=models.Index(fields=['tenant', 'state', 'due_at'], name='tenancy_acc_tenant__639376_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('state', 'COMPLETED')), models.Q(('state', 'COMPLETED'), _negated=True), _connector='OR'), name='completed_access_review_has_time'),
        ),
        migrations.AddIndex(
            model_name='accessreviewitem',
            index=models.Index(fields=['review', 'decision', 'remediation_state'], name='tenancy_acc_review__283d71_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessreviewitem',
            constraint=models.UniqueConstraint(fields=('review', 'source_object_id'), name='uniq_review_assignment'),
        ),
        migrations.AddConstraint(
            model_name='accessreviewitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'EXCEPTION'), ('exception_expires_at__isnull', False), ('exception_owner__isnull', False)), models.Q(('decision', 'EXCEPTION'), _negated=True), _connector='OR'), name='review_exception_is_bounded'),
        ),
    ]
