# Generated by Django 5.2.17 on 2026-09-30 05:57

import django.db.models.deletion
import modules.search.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiting', '0003_foundation_rls'),
        ('tenancy', '0005_emergencyaccessrequest_tenant_admin_notified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_id', models.UUIDField()),
                ('purpose', models.CharField(choices=[('REQUIREMENT', 'Requirement'), ('PREFERENCE', 'Preference'), ('EXCLUSION', 'Exclusion')], max_length=20)),
                ('operator', models.CharField(choices=[('ANY', 'Any'), ('ALL', 'All')], max_length=3)),
                ('label', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SearchDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(blank=True, max_length=4000)),
                ('context_type', models.CharField(choices=[('AD_HOC', 'Ad Hoc'), ('OPENING', 'Opening')], max_length=10)),
                ('criteria_context', models.JSONField()),
                ('result_limit', models.PositiveSmallIntegerField(default=25)),
                ('expires_at', models.DateTimeField(default=modules.search.models.expires_in_seven_days)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('derived_opening', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='recruiting.opening')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('search', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='search.searchdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_id', models.UUIDField()),
                ('field', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=20)),
                ('value', models.JSONField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='search.criteriagroup')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='search.searchdefinition')),
            ],
        ),
        migrations.AddField(
            model_name='criteriagroup',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='search.searchdefinition'),
        ),
        migrations.CreateModel(
            name='SearchResultSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_profile_id', models.UUIDField()),
                ('ordinal', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=3, max_digits=8)),
                ('evidence', models.JSONField(default=list)),
                ('unknowns', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='search.searchdefinition')),
            ],
        ),
        migrations.AddIndex(
            model_name='searchdefinition',
            index=models.Index(fields=['tenant', 'actor', 'created_at'], name='search_sear_tenant__9e5b64_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchdefinition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('context_type', 'AD_HOC'), ('derived_opening__isnull', True)), models.Q(('context_type', 'OPENING'), ('derived_opening__isnull', False)), _connector='OR'), name='search_context_opening_shape'),
        ),
        migrations.AddConstraint(
            model_name='searchdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('result_limit__gte', 1), ('result_limit__lte', 100)), name='search_result_limit_range'),
        ),
        migrations.AddConstraint(
            model_name='savedsearch',
            constraint=models.UniqueConstraint(fields=('tenant', 'actor', 'name'), name='uniq_actor_saved_search_name'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.UniqueConstraint(fields=('search', 'stable_id'), name='uniq_search_criterion'),
        ),
        migrations.AddConstraint(
            model_name='criteriagroup',
            constraint=models.UniqueConstraint(fields=('search', 'stable_id'), name='uniq_search_group'),
        ),
        migrations.AddConstraint(
            model_name='searchresultsnapshot',
            constraint=models.UniqueConstraint(fields=('search', 'candidate_profile_id'), name='uniq_search_candidate_result'),
        ),
        migrations.AddConstraint(
            model_name='searchresultsnapshot',
            constraint=models.UniqueConstraint(fields=('search', 'ordinal'), name='uniq_search_result_ordinal'),
        ),
    ]
