# Generated by Django 5.2.17 on 2026-10-01 11:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def secure(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("""
          ALTER TABLE search_searchworkflowhandoff ENABLE ROW LEVEL SECURITY;
          ALTER TABLE search_searchworkflowhandoff FORCE ROW LEVEL SECURITY;
          CREATE POLICY tenant_isolation ON search_searchworkflowhandoff
          USING (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
          WITH CHECK (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);
        """)


def unsecure(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("DROP POLICY tenant_isolation ON search_searchworkflowhandoff")


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_sessioncredential_stepupevidence_and_more"),
        ("operations", "0003_workflowrun"),
        ("search", "0005_savedsearch_result_context_snapshot_and_more"),
        ("tenancy", "0007_access_review_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchWorkflowHandoff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("criteria-review", "Criteria review"),
                            ("search-results", "Search results"),
                        ],
                        max_length=20,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("retry_hash", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                ("payload_ciphertext", models.BinaryField()),
                ("resource_version", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("REVOKED", "Revoked"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="identity.sessioncredential"
                    ),
                ),
                (
                    "search",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search.searchdefinition",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenancy.tenant"
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operations.workflowrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("credential", "retry_hash"), name="uniq_handoff_retry"
                    )
                ],
            },
        ),
        migrations.RunPython(secure, unsecure),
    ]
