# Generated by Django 5.2.17 on 2026-10-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0006_workflow_handoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchworkflowhandoff",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="searchworkflowhandoff",
            name="kind",
            field=models.CharField(
                choices=[
                    ("criteria-review", "Criteria review"),
                    ("search-results", "Search results"),
                    ("comparison-selection", "Comparison selection"),
                ],
                max_length=20,
            ),
        ),
    ]
