# Generated by Django 5.2.17 on 2026-09-29 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key_hash', models.BinaryField(unique=True)),
                ('provider_session_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('provider', models.CharField(editable=False, max_length=80)),
                ('assurance', models.CharField(choices=[('VERIFIED_EMAIL_OTP', 'Verified Email Otp'), ('WORKFORCE_MFA', 'Workforce Mfa')], editable=False, max_length=40)),
                ('refresh_token_ciphertext', models.BinaryField(null=True)),
                ('authenticated_at', models.DateTimeField(editable=False)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('revoked_at', models.DateTimeField(editable=False, null=True)),
                ('revocation_reason', models.CharField(blank=True, editable=False, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StepUpEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(editable=False, max_length=100)),
                ('method', models.CharField(choices=[('VERIFIED_EMAIL_OTP', 'Verified Email Otp'), ('WORKFORCE_MFA', 'Workforce Mfa')], editable=False, max_length=40)),
                ('nonce_hash', models.BinaryField(unique=True)),
                ('verified_at', models.DateTimeField(editable=False)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('revoked_at', models.DateTimeField(editable=False, null=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_up_events', to=settings.AUTH_USER_MODEL)),
                ('session_credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_up_events', to='identity.sessioncredential')),
            ],
        ),
        migrations.AddIndex(
            model_name='sessioncredential',
            index=models.Index(fields=['identity', 'revoked_at', 'expires_at'], name='identity_se_identit_673c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='stepupevidence',
            index=models.Index(fields=['identity', 'purpose', 'expires_at'], name='identity_st_identit_e002c2_idx'),
        ),
    ]
