export const applicationName = "Enter";

import "../styles/forms.css";
import "../styles/responsive.css";
import "../styles/candidate-profile.css";
import "../styles/candidate-applications.css";
import "../candidate/profile";
import "../candidate/resume";
import "../candidate/rights-center";
import "../candidate/application";
import "../candidate/progress";
import "../styles/recruiter-search.css";
import "../styles/recruiter-management.css";
import "../recruiter/search";
import "../recruiter/criteria-review";
import "../recruiter/speech-search";
import "../recruiter/candidate-findings";
import "../recruiter/candidate-detail";
import "./navigation";
import "./persistence";
