# Generated by Django 5.2.17 on 2026-09-29 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(null=True)),
                ('candidate_profile_id', models.UUIDField(null=True)),
                ('application_id', models.UUIDField(null=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'Whatsapp')], max_length=20)),
                ('template_key', models.CharField(max_length=160)),
                ('template_version', models.CharField(max_length=40)),
                ('destination_ciphertext', models.BinaryField()),
                ('consent_basis', models.CharField(max_length=120)),
                ('state', models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('first_attempt_at', models.DateTimeField(null=True)),
                ('next_attempt_at', models.DateTimeField(null=True)),
                ('terminal_error_category', models.CharField(blank=True, max_length=80)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'next_attempt_at', 'created_at'], name='communicati_state_5166af_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeadLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('failure_category', models.CharField(max_length=80)),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('redriven_at', models.DateTimeField(null=True)),
                ('redriven_by_id', models.UUIDField(null=True)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='communications.notification')),
            ],
        ),
    ]
