# Generated by Django 5.2.17 on 2026-09-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_notification_rls'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__lte', 5)), name='notification_attempts_max_5'),
        ),
    ]
